#! /bin/bash

for a in 0 1 2 3 4 5 6 7 8 9 a b c d e f; do
    for b in 0 1 2 3 4 5 6 7 8 9 a b c d e f; do
	for c in 0 1 2 3 4 5 6 7 8 9 a b c d e f; do
	    for d in 0 1 2 3 4 5 6 7 8 9 a b c d e f; do
		branch=$a$b$c$d
		git checkout -b $branch master && date >> date && git add date && git commit -m "Added date at $(date)" && git push origin --set-upstream $branch
		exit 0
	    done
	done
    done
done
